machines:
  wisteria-o:
    login_host: wisteria
    work_dir: /work/gc64/c64050
    kochi_root: /work/gc64/c64050/.kochi
    alloc_interact_script:
      - n_nodes=$(echo $KOCHI_ALLOC_NODE_SPEC | cut -f 1 -d ":" | sed 's/x/*/g' | bc)
      - pjsub --interact --sparam wait-time=unlimited -j -g gc64 -L rscgrp=interactive-o,node=$KOCHI_ALLOC_NODE_SPEC --mpi proc=$((n_nodes * 48))
    alloc_script:
      - n_nodes=$(echo $KOCHI_ALLOC_NODE_SPEC | cut -f 1 -d ":" | sed 's/x/*/g' | bc)
      - echo "$KOCHI_WORKER_LAUNCH_CMD" | pjsub -X -j -g gc64 -L rscgrp=regular-o,node=$KOCHI_ALLOC_NODE_SPEC,elapse=${KOCHI_ALLOC_TIME_LIMIT:-6:00:00} --mpi proc=$((n_nodes * 48))
    load_env_script:
      on_login_node: |
        module load odyssey > /dev/null
        export MPICC=mpifccpx
        export MPICXX=mpiFCCpx
        export fccpx_ENV="-Nclang -Knolargepage"
        export FCCpx_ENV="-Nclang -Knolargepage"
        module load cmake/3.22.2
      on_machine: |
        export PATH="/work/gc64/c64050/opt/odyssey/tmux/3.3a/bin:$PATH"
        . /work/gc64/c64050/venv/odyssey/bin/activate
        export MPICC=mpifcc
        export MPICXX=mpiFCC
        export fcc_ENV="-Nclang -Knolargepage"
        export FCC_ENV="-Nclang -Knolargepage"
        module load cmake/3.22.2
        export PYTHONPATH="/usr/share/gcc-8/python:${PYTHONPATH:+$PYTHONPATH}" # workaround for gdb bug (module 'libstdcxx' not found)

  ito-a:
    login_host: ito
    alloc_script: |
      if (( $KOCHI_ALLOC_NODE_SPEC == 1 )); then
        rscgrp=ito-ss
      elif (( $KOCHI_ALLOC_NODE_SPEC <= 4 )); then
        rscgrp=ito-s
      elif (( $KOCHI_ALLOC_NODE_SPEC <= 16 )); then
        rscgrp=ito-m
      elif (( $KOCHI_ALLOC_NODE_SPEC <= 64 )); then
        rscgrp=ito-l
      elif (( $KOCHI_ALLOC_NODE_SPEC <= 128 )); then
        rscgrp=ito-xl
      elif (( $KOCHI_ALLOC_NODE_SPEC <= 256 )); then
        rscgrp=ito-xxl
      else
        echo "Allocating $KOCHI_ALLOC_NODE_SPEC nodes is not allowed on ITO."
        exit 1
      fi
      echo "$KOCHI_WORKER_LAUNCH_CMD" | pjsub -j -o /dev/null -L rscunit=ito-a,rscgrp=$rscgrp,vnode=$KOCHI_ALLOC_NODE_SPEC,vnode-core=36,elapse=${KOCHI_ALLOC_TIME_LIMIT:-6:00:00}
    load_env_script: |
      module load python/3.6.2
      . ~/venv/ito-a/bin/activate
      export PATH=$HOME/opt/gcc/11.2.0/bin:$PATH
      export LD_LIBRARY_PATH=$HOME/opt/gcc/11.2.0/lib64:$LD_LIBRARY_PATH
      export MPICC=mpicc
      export MPICXX=mpicxx
      module load cmake/3.18.2

  squid-c:
    login_host: squid
    work_dir: /sqfs/work/G15442/v60680
    kochi_root: /sqfs/work/G15442/v60680/.kochi
    alloc_interact_script: |
      qlogin -q INTC --group=G15442 -b $KOCHI_ALLOC_NODE_SPEC -T openmpi
    alloc_script: |
      echo "$KOCHI_WORKER_LAUNCH_CMD" | qsub -q SQUID -j o --group=G15442 -b $KOCHI_ALLOC_NODE_SPEC -T openmpi -l elapstim_req=${KOCHI_ALLOC_TIME_LIMIT:-6:00:00}
    load_env_script:
      on_login_node: |
        . /sqfs/work/G15442/v60680/venv/squid-c/bin/activate
        export TERM=xterm-256color
        export MPICC=mpicc
        export MPICXX=mpicxx
      on_machine: |
        . /sqfs/work/G15442/v60680/venv/squid-c/bin/activate
        export TERM=xterm-256color
        export MPICC=mpicc
        export MPICXX=mpicxx
        (module load BaseGCC/2022; mpirun -N 1 $NQSV_MPIOPTS /sqfs/home/v60680/launch_sshd.sh)

dependencies:
  ucx:
    recipes:
      - name: v1.11.0
        before_script: UCX_VERSION=1.11.0 CONFIGURE_OPTS="--disable-logging --disable-debug --disable-assertions --disable-params-check"
      - name: v1.13.1
        before_script: UCX_VERSION=1.13.1 CONFIGURE_OPTS="--disable-logging --disable-debug --disable-assertions --disable-params-check"
      - name: v1.11.0-debug
        before_script: UCX_VERSION=1.11.0 CONFIGURE_OPTS="--enable-debug --enable-debug-data" CFLAGS="${CFLAGS:+$CFLAGS} -O0"
      - name: v1.13.1-debug
        before_script: UCX_VERSION=1.13.1 CONFIGURE_OPTS="--enable-debug --enable-debug-data" CFLAGS="${CFLAGS:+$CFLAGS} -O0"
      - name: v1.11.0-prof
        before_script: UCX_VERSION=1.11.0 CONFIGURE_OPTS="--disable-logging --disable-debug --disable-assertions --disable-params-check --enable-profiling --enable-frame-pointer --enable-stats"
    script:
      - unset MPICC
      - unset MPICXX
      - wget https://github.com/openucx/ucx/releases/download/v${UCX_VERSION}/ucx-${UCX_VERSION}.tar.gz
      - tar xvf ucx-${UCX_VERSION}.tar.gz
      - cd ucx-${UCX_VERSION}/
      - ./configure CFLAGS="${CFLAGS:+$CFLAGS} -gdwarf-4" --prefix=$KOCHI_INSTALL_PREFIX ${CONFIGURE_OPTS:+$CONFIGURE_OPTS}
      - make -j
      - make install

  openmpi:
    git: https://github.com/open-mpi/ompi.git
    depends:
      - name: ucx
        recipe: v1.11.0
    recipes:
      - name:   main
        branch: main
      - name:   v5.0.0rc7
        branch: v5.0.0rc7
      - name:   v5.0.0rc9
        branch: v5.0.0rc9
      - name:   v5.0.0rc7-debug
        branch: v5.0.0rc7
        before_script: CONFIGURE_OPTS="--enable-debug" CFLAGS="${CFLAGS:+$CFLAGS} -O0"
        depends:
          - name: ucx
            recipe: v1.11.0-debug
      - name:   v5.0.0rc9-debug
        branch: v5.0.0rc9
        before_script: CONFIGURE_OPTS="--enable-debug" CFLAGS="${CFLAGS:+$CFLAGS} -O0"
        depends:
          - name: ucx
            recipe: v1.13.1-debug
    script:
      - ./autogen.pl
      - mkdir build
      - cd build/
      - CFLAGS="${CFLAGS:+$CFLAGS} -g -gdwarf-4"
      - ../configure ${CFLAGS:+CFLAGS="$CFLAGS"} --prefix=$KOCHI_INSTALL_PREFIX --with-ucx=$KOCHI_INSTALL_PREFIX_UCX --disable-man-pages --with-pmix=internal --with-hwloc=internal --with-libevent=internal --without-hcoll --enable-mca-no-build=mtl-ofi ${CONFIGURE_OPTS:+$CONFIGURE_OPTS}
      - make -j
      - make install
    activate_script:
      - export PATH=$KOCHI_INSTALL_PREFIX_OPENMPI/bin${PATH:+:$PATH}
      - export LD_LIBRARY_PATH=$KOCHI_INSTALL_PREFIX_OPENMPI/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

  massivethreads-dm:
    git: git@gitlab.eidos.ic.i.u-tokyo.ac.jp:shiina/massivethreads-dm.git
    depends:
      - name: openmpi
        recipe: v5.0.0rc7
        machines: [local]
      - name: openmpi
        recipe: v5.0.0rc9
        machines: [ito-a]
      - name: openmpi
        recipe: main
        machines: [squid-c]
    recipes:
      - name: release
        branch: ityr
        script:
          - CFLAGS="${CFLAGS:+$CFLAGS} -O3 -g -gdwarf-4 -Wall"
          - CCFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" ./configure MPICC=$MPICC MPICXX=$MPICXX $CONFIGURE_OPTS --with-comm-layer=mpi3 --prefix=$KOCHI_INSTALL_PREFIX
      - name: develop
        git: ../massivethreads-dm
        current_state: true
        script:
          - CFLAGS="${CFLAGS:+$CFLAGS} -O3 -g -gdwarf-4 -Wall"
          - CCFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" ./configure MPICC=$MPICC MPICXX=$MPICXX $CONFIGURE_OPTS --with-comm-layer=mpi3 --prefix=$KOCHI_INSTALL_PREFIX
    before_script: |
      $MPICXX --version
      if [[ $KOCHI_MACHINE == wisteria-o ]]; then
        CFLAGS="${CFLAGS:+$CFLAGS} -DMADI_NULLIFY_PARENT_STACK=1"
        CONFIGURE_OPTS="${CONFIGURE_OPTS:+$CONFIGURE_OPTS} --host=aarch64"
      fi
      if [[ $KOCHI_MACHINE == local ]]; then
        CONFIGURE_OPTS="${CONFIGURE_OPTS:+$CONFIGURE_OPTS} --enable-polling"
      fi
    after_script:
      - make -j
      - make install

  pcas:
    git: git@gitlab.eidos.ic.i.u-tokyo.ac.jp:shiina/pcas.git
    depends:
      - name: openmpi
        recipe: v5.0.0rc7
        machines: [local]
      - name: openmpi
        recipe: v5.0.0rc9
        machines: [ito-a]
      - name: openmpi
        recipe: main
        machines: [squid-c]
    recipes:
      - name: release
        branch: master
      - name: develop
        git: ../pcas
        current_state: true
      - name: develop_test
        git: ../pcas
        current_state: true
        on_machine: true
        script:
          - CC=$MPICC CXX=$MPICXX cmake -DCMAKE_INSTALL_PREFIX=$KOCHI_INSTALL_PREFIX .
          - make all test install
    script:
      - CC=$MPICC CXX=$MPICXX cmake -DCMAKE_INSTALL_PREFIX=$KOCHI_INSTALL_PREFIX -DBUILD_TESTING=OFF .
      - make install

  massivelogger:
    git: https://github.com/massivethreads/massivelogger.git
    recipes:
      - name: release
        branch: master
      - name: develop
        git: ../massivelogger
        current_state: true
    script:
      - rm -rf $KOCHI_INSTALL_PREFIX/*
      - cp -af . $KOCHI_INSTALL_PREFIX

  libunwind:
    recipes:
      - name: v1.6.2
        before_script: LIBUNWIND_VERSION=1.6.2
    script:
      - wget http://download.savannah.nongnu.org/releases/libunwind/libunwind-${LIBUNWIND_VERSION}.tar.gz
      - tar xvf libunwind-${LIBUNWIND_VERSION}.tar.gz
      - cd libunwind-${LIBUNWIND_VERSION}/
      - if [[ $KOCHI_MACHINE == wisteria-o ]]; then
      -   ./configure CC=fccpx CXX=FCCpx --prefix=$KOCHI_INSTALL_PREFIX --host=aarch64-linux-gnu
      - else
      -   ./configure --prefix=$KOCHI_INSTALL_PREFIX
      - fi
      - make -j
      - make install

  backward-cpp:
    git: https://github.com/bombela/backward-cpp
    depends:
      - name: libunwind
        recipe: v1.6.2
    recipes:
      - name:   v1.6
        branch: v1.6
    script:
      - mkdir -p $KOCHI_INSTALL_PREFIX/include
      - cp backward.hpp $KOCHI_INSTALL_PREFIX/include/

  jemalloc:
    recipes:
      - name: v5.3.0
        envs:
          JEMALLOC_VERSION: 5.3.0
          CONFIGURE_OPTS: ""
      - name: v5.3.0-prof
        envs:
          JEMALLOC_VERSION: 5.3.0
          CONFIGURE_OPTS: --enable-prof
    script:
      - wget https://github.com/jemalloc/jemalloc/releases/download/${JEMALLOC_VERSION}/jemalloc-${JEMALLOC_VERSION}.tar.bz2
      - tar xvf jemalloc-${JEMALLOC_VERSION}.tar.bz2
      - cd jemalloc-${JEMALLOC_VERSION}/
      - if [[ $KOCHI_MACHINE == wisteria-o ]]; then
      -   CONFIGURE_OPTS="${CONFIGURE_OPTS:+$CONFIGURE_OPTS} CC=fccpx CXX=FCCpx --host=aarch64-linux-gnu --with-lg-page=16"
      - fi
      - ./configure --prefix=$KOCHI_INSTALL_PREFIX $CONFIGURE_OPTS
      - make -j
      - make install

  boost:
    recipes:
      - name: v1.80.0
        envs:
          BOOST_VERSION: 1.80.0
    script: |
      BOOST_NAME=boost_$(sed 's/\./_/g' <<< $BOOST_VERSION)
      wget -q https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION}/source/${BOOST_NAME}.tar.bz2
      tar xf ${BOOST_NAME}.tar.bz2
      cd ${BOOST_NAME}/
      ./bootstrap.sh --prefix=$KOCHI_INSTALL_PREFIX
      if [[ $KOCHI_MACHINE == wisteria-o ]]; then
        echo "using clang : fcc : FCCpx ;" > user-config.jam
        CONFIGURE_OPTS="${CONFIGURE_OPTS:+$CONFIGURE_OPTS} --user-config=user-config.jam toolset=clang-fcc"
      fi
      ./b2 --without-python pch=off ${CONFIGURE_OPTS:+$CONFIGURE_OPTS} -j $(nproc) install

  pcg:
    git: https://github.com/imneme/pcg-cpp.git
    recipes:
      - name: master
        branch: master
    script:
      - cp -r include/ $KOCHI_INSTALL_PREFIX/

  # experimental
  itoyori:
    git: ../itoyori
    current_state: true
    on_machine: true
    depends:
      - name: openmpi
        recipe: v5.0.0rc7
        machines: [local]
      - name: openmpi
        recipe: v5.0.0rc9
        machines: [ito-a]
    recipes:
      - name: develop
    script:
      - CC=$MPICC CXX=$MPICXX cmake -DCMAKE_INSTALL_PREFIX=$KOCHI_INSTALL_PREFIX .
      - make all test install
